:basedir: ../../..
include::{basedir}/_common.adoc[]

[[chapter:activator]]
== Activator
This chapter covers the Activator API of the SCION Microfrontend Platform.

[.chapter-toc]
****
[.chapter-title]
In this Chapter

- <<chapter:activator:what-is-an-activator>>
- <<chapter:activator:context>>
- <<chapter:activator:multiple-activators>>
- <<chapter:activator:signaling-readiness>>
- <<chapter:activator:sharing-state>>

****
'''

[[chapter:activator:what-is-an-activator]]
[discrete]
=== What is an Activator?
An activator allows a micro application to initialize and connect to the platform upon host application's startup, i.e., when the user loads the web application into the browser. An activator is a startup hook for micro applications to initialize or register message or intent handlers. In the broadest sense, an activator is a kind of microfrontend, i.e. an HTML page that runs in an iframe. In contrast to regular microfrontends, however, at platform startup, the platform loads activator microfrontends into hidden iframes for the entire platform lifecycle, thus, providing a stateful session to the micro application on the client-side.

====
An activator is loaded into the browser exactly once, for the entire lifecycle of the application. Some typical use cases for activators include <<chapter:intent-based-messaging:receiving-intents,handling intents>> and <<chapter:topic-based-messaging:receiving-messages,messages>>, preloading data, or <<chapter:intention-api:capability-registration,flexibly providing capabilities>>. If implementing single sign-on authentication, you could, for example, obtain the user's access token and preemptively refresh it before its expected expiration.
====

A micro application registers an activator as public _activator_ capability in its manifest, as follows:

[source,json]
----
include::activator.snippets.ts[tags=register-activator]
----
<1> Activators have the type `activator`.
<2> Activators must have public visibility.
<3> Path where the platform can load the activator microfrontend. The path is relative to the base URL of the micro application, as specified in the application manifest.

[[chapter:activator:context]]
[discrete]
=== Activation Context
An activator's microfrontend runs inside an activation context. The context provides access to the activator capability, allowing to read properties declared on the activator capability.

You can obtain the activation context using the `ContextService` as following.

[source,typescript]
----
include::activator.snippets.ts[tags=activation-context]
----

[[chapter:activator:multiple-activators]]
[discrete]
=== Multiple Activators
A micro application can register multiple activators. Note, that each activator boots the micro application on its own and runs in a separate browsing context. The platform nominates one activator of each micro application as its primary activator. The nomination has no relevance to the platform but can help code decide whether or not to install singleton functionality.

You can test if running in the primary activation context as following.

[source,typescript]
----
include::activator.snippets.ts[tags=activation-context:primary]
----

[[chapter:activator:signaling-readiness]]
[discrete]
=== Signaling Readiness
Starting an activator may take some time. In order not to miss any messages or intents, you can instruct the platform host to wait to enter started state until you signal the activator to be ready.

For this purpose, you can define a set of topics where to publish a ready message to signal readiness. If you specify multiple topics, the activator enters ready state after you have published a ready message to all these topics. A ready message is an event; thus, a message without payload.

If not specifying a readiness topic, the platform host does not wait for this activator to become ready. However, if you specify a readiness topic, make sure that your activator has a fast startup time and signals readiness as early as possible not to delay the startup of the platform host. Optionally, you can configure a <<objects::microfrontend-platform-config:activatorLoadTimeout,maximum time>> that the host waits for an application to signal readiness. For more information, refer to chapter <<chapter:configuration:configuring-the-platform>>.

[source,json]
----
include::activator.snippets.ts[tags=register-activator-with-readiness-topic]
----
<1> Specifies one or more readiness topics. Activators of different applications can publish their readiness status on the same topic. The platform checks from which activator received readiness messages originate.

In the activator, when you are ready, you can signal your readiness as follows:

[source,typescript]
----
include::activator.snippets.ts[tags=signal-readiness]
----

Alternatively, you can read the configured readiness topic directly from the activator capability. However, this only works if you specify a single readiness topic.

[source,typescript]
----
include::activator.snippets.ts[tags=signal-readiness:read-topic-from-capability]
----

[[chapter:activator:sharing-state]]
[discrete]
=== Sharing State
Since an activator runs in a separate browsing context, microfrontends cannot directly access its state. Instead, an activator could put data, for example, into session storage, so that microfrontends of its micro application can access it. Alternatively, an activator could install a message listener, allowing microfrontends to request data via client-side messaging. For more information, refer to <<chapter:cross-application-communication>>.

