:basedir: ../../..
include::{basedir}/_common.adoc[]

[[chapter:router-outlet]]
== Router Outlet
The Router Outlet is a web component that allows embedding web content using the router.

[.chapter-toc]
****
[.chapter-title]
In this Chapter

- <<chapter:router-outlet:concepts-and-usage>>
- <<chapter:router-outlet:outlet-size>>
- <<chapter:router-outlet:scrollable-content>>
- <<chapter:router-outlet:keystroke-bubbling>>
- <<chapter:router-outlet:router-outlet-events>>
- <<chapter:router-outlet:outlet-context>>
- <<chapter:router-outlet:splash>>
- <<chapter:router-outlet:router-outlet-api>>
****
'''

[[chapter:router-outlet:concepts-and-usage]]
[discrete]
=== Concepts and Usage
Embedding web content using an iframe can quickly become a daunting task. For this reason, the SCION Microfrontend Platform provides a router outlet that solves many of the cumbersome quirks of iframes.

The router outlet is a web component that wraps an iframe. It can be used like a native HTML element. As its name suggests, the web content of the outlet is controlled by a router. The router is a platform service, allowing you to set the URL of an outlet from anywhere in the application, even across application boundaries. When adding the outlet to the DOM, the outlet displays the last URL routed for it, if any. When repeating routing for an outlet, its content is replaced.

The router outlet can be added to a HTML page as follows.

[source,html]
----
include::outlet.snippets.ts[tags=router-outlet]
----

To display web content in the outlet, navigate to the URL using the router, as follows:

[source,typescript]
----
include::outlet.snippets.ts[tags=outlet-router]
----

As an alternative to navigating directly to a URL, the router supports navigation to a microfrontend capability via an intent. For more information, refer to <<chapter:outlet-router:navigation-via-intent>>. Routing is explained in more detail in chapter <<chapter:routing>>.

NOTE: If no content is routed for display in the router outlet, the CSS class `sci-empty` is added to the outlet. An outlet does not display content if no navigation has taken place yet, or if the outlet content has been cleared.

'''

The host application typically adds one or more top-level router outlets to its main application shell.

[.text-center]
image::top-level-router-outlets.svg[]

<1> _PRIMARY_ outlet to display the main content
<2> _ASIDE_ outlet to display context sensitive content

Outlets can be nested, allowing a microfrontend to embed another microfrontend. There is no limit to the number of nested outlets. However, be aware that nested content is loaded cascaded, that is, only loaded once its parent content finished loading.

The following figure shows a microfrontend that embeds another microfrontend.

[.text-center]
image::nested-router-outlets.svg[]

[[chapter:router-outlet:outlet-size]]
[discrete]
=== Outlet size
The router outlet can adapt its size to the preferred size of its embedded content. The preferred size is set by the microfrontend embedded in the router outlet, which, therefore, requires the embedded microfrontend to be connected to the platform. For detailed instructions on how to register a micro application and connect to the plaform, refer to the chapter <<chapter:configuration>>.

NOTE: The preferred size of an element is the minimum size that allows it to display normally. Setting a preferred size is useful if the outlet is displayed in a layout that aligns its items based on the items' content size.

Embedded content can report its preferred size using the `PreferredSizeService`, causing the outlet to change its size.

[source,typescript]
----
include::outlet.snippets.ts[tags=router-outlet:preferred-size]
----

In addition to explicitly setting the preferred size, the platform provides a convenience API to bind a DOM element via `PreferredSizeService.fromDimension` to automatically report its content size as preferred size to the outlet.

[source,typescript]
----
include::outlet.snippets.ts[tags=router-outlet:preferred-size-fromDimension]
----

_Prerequisites for the element used as outlet size provider:_

- The element to be observed via `PreferredSizeService.fromDimension` must behave as block-level box and not as inline-level box. So, if you want to observe an inline element, set its display type to either `block` or `inline-block`.
- If the element to be observed should not fill the remaining space and may change in size, we recommend taking it out of the document element flow, i.e., position it absolutely without defining a width and height. Otherwise, once the element has reported a preferred size, it could not shrink below that size.

[[chapter:router-outlet:scrollable-content]]
[discrete]
=== Scrollable Content
By default, page scrolling is enabled for the embedded content, displaying a scrollbar when it overflows. If disabled, overflowing content is clipped, unless the embedded content uses a viewport, or reports its preferred size to the outlet.

The below code snippet illustrates how to disable page scrolling for the embedded content.

[source,html]
----
include::outlet.snippets.ts[tags=router-outlet:page-scrolling-disabled]
----

[[chapter:router-outlet:keystroke-bubbling]]
[discrete]
=== Keystroke Bubbling
The router outlet allows the registration of keystrokes, instructing embedded content at any nesting level to propagate corresponding keyboard events to this outlet.

The outlet dispatches keyboard events for registered keystrokes as synthetic, untrusted keyboard events via its event dispatcher. They bubble up the DOM tree like regular events. Propagated events are of the original type, meaning that when the user presses a key on the keyboard, a `keydown` keyboard event is dispatched, or a `keyup` event when releasing a key, respectively.

A keystroke has the following syntax.
[.text-center]
image::keystroke-syntax.svg[]

A keystroke is a `string` that has several parts, each separated with a dot. The first part specifies the event type (`keydown` or `keyup`), followed by optional modifier part(s) (`alt`, `shift`, `control`, `meta`, or a combination thereof) and with the keyboard key as the last part. The key is a case-insensitive value of the `KeyboardEvent.key` property. Two keys are an exception to the value of the `KeyboardEvent.key` property: `dot` and `space`.

TIP: For a complete list of valid key values, see link:https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values[window=\"_blank\"].

The keystroke behavior can be controlled via flags, a dictionary of key-value pairs. Flags are optional. Multiple flags are separated by a semicolon. The following flags are supported:

.Supported keystroke flags
[cols="1,1,1,2,2"]
|===
| Flag | Supported Values | Default if not set | Description | Example

| preventDefault
a| `true`, `false`
a| `false`
| allows preventing the browser's default action
a| `{preventDefault=true}`

|===

You can register keystrokes on a `<sci-router-outlet>` as follows. Multiple keystrokes are separated with a comma.

[source,html]
----
include::outlet.snippets.ts[tags=router-outlet:keystrokes-html-template]
----

Alternatively, you can register keystrokes on the DOM element as shown below.
[source,typescript]
----
include::outlet.snippets.ts[tags=router-outlet:keystrokes-typescript]
----

[[chapter:router-outlet:router-outlet-events]]
[discrete]
=== Router Outlet Events
The router outlet emits the following events as custom DOM events. You can attach an event listener declaratively in the HTML template using the `onevent` handler syntax, or programmatically using the `addEventListener` method.

activate::
The `activate` custom DOM event is fired when a microfrontend is mounted. It contains the URL of the mounted microfrontend in its `details` property as `string` value. The microfrontend may not be fully loaded yet.

deactivate::
The `deactivate` custom DOM event is fired when a microfrontend is about to be unmounted. It contains the URL of the unmounted microfrontend in its `details` property as `string` value.

focuswithin::
The `focuswithin` custom DOM event is fired when the microfrontend loaded into the outlet, or any of its child microfrontends, has gained or lost focus. It contains the current focus-within state in its `details` property as a `boolean` value: `true` if focus was gained, or `false` if focus was lost.
+
The event does not bubble up through the DOM. After gaining focus, the event is not triggered again until the embedded content loses focus completely, i.e., when focus does not remain in the embedded content at any nesting level. This event behaves like the `:focus-within` CSS pseudo-class but operates across iframe boundaries. For example, it can be useful when implementing overlays that close upon focus loss.

NOTE: Note that SCION can only monitor the focus of microfrontends that are connected to the platform.

[discrete]
=== Examples for subscribing to router-outlet events

The following example attaches an event listener in the HTML template.
[source,html]
----
include::outlet.snippets.ts[tags=router-outlet:listen-to-event-in-template]
----

For an Angular application, it would look as follows:
[source,html]
----
include::outlet.snippets.ts[tags=router-outlet:listen-to-event-in-template-angular]
----

The example below adds an event listener programmatically.
[source,typescript]
----
include::outlet.snippets.ts[tags=router-outlet:listen-to-event-programmatically]
----

[[chapter:router-outlet:outlet-context]]
[discrete]
=== Outlet Context
The router outlet allows associating contextual data, which then is available to embedded content at any nesting level. Data must be serializable with the structured clone algorithm. Embedded content can look up contextual data using the `ContextService`. Typically, contextual data is used to provide microfrontends with information about their embedding environment.

Each outlet spans a new context. A context is like a `Map` with key-value entries. Contexts form a hierarchical tree structure. When looking up a value and if the value is not found in the current context, the lookup is retried on the parent context, repeating until either a value is found, or the root of the context tree has been reached.

'''

Imagine a tabbar with tabs implemented as a microfrontend. As an example, a microfrontend should highlight its tab in the tabbar when its data changes. For each tab, you can define a random highlighting topic and put it to the context of the tab router outlet. The microfrontend can then send an event to that topic when its data changes.

[source,typescript]
----
include::outlet.snippets.ts[tags=router-outlet:set-context-value]
----
<1> Generates some random UUID.
<2> Puts the UUID to the context.

Embedded microfrontend can then read the `highlighting-topic` from the current context and send an event to that topic when its data changes.

[source,typescript]
----
include::outlet.snippets.ts[tags=router-outlet:observe-context-value]
----
<1> Looks up the `highlighting-topic` from the current context.
<2> Sends an event to the `highlighting-topic` when its data changes.

[[chapter:router-outlet:splash]]
[discrete]
=== Splash
Loading and bootstrapping a microfrontend can take some time, at worst, only displaying content once initialized. To indicate the loading of a microfrontend, the navigator can instruct the router outlet to display a splash until the microfrontend signals readiness.

[source,typescript]
----
include::outlet.snippets.ts[tags=router-outlet:show-splash-flag]
----

The splash is the markup between the opening and closing tags of the router outlet element.

[source,html]
----
include::outlet.snippets.ts[tags=router-outlet:splash]
----

The splash is displayed until the embedded microfrontend signals readiness.

[source,typescript]
----
include::outlet.snippets.ts[tags=router-outlet:signal-readiness]
----

To lay out the content of the splash use the pseudo-element selector `::part(splash)`.

Example of centering splash content in a CSS grid container:

[source,typescript]
----
include::outlet.snippets.ts[tags=router-outlet:lay-out-splash-content]
----

****
TIP: If the application explicitly sets the CSS color scheme (e.g., because of support for different themes), we recommend showing a splash. Otherwise, if the microfrontend and the host use different color schemes, the iframe is no longer transparent, causing unwanted flickering particularly while loading the microfrontend. See https://github.com/w3c/csswg-drafts/issues/4772#issuecomment-591553929 for more information.
****

[[chapter:router-outlet:router-outlet-api]]
[discrete]
=== Router Outlet API
You can find the full list of available properties and methods of `SciRouterOutletElement` in the  link:{typedoc-url}/classes/SciRouterOutletElement.html[TypeDoc, window=\"_blank\"].

TIP: To hide inherited properties and methods of the `HTMLElement` in the TypeDoc, uncheck the `Inherited` checkbox in the upper right corner of the _TypeDoc_.

