:basedir: ../..
include::{basedir}/_common.adoc[]

[[chapter:configuration]]
== Configuration and Startup

This chapter describes how to configure and start the SCION Microfrontend Platform.

[.chapter-toc]
****
[.chapter-title]
In this Chapter

- <<chapter:configuration:starting-the-platform-in-host-application>>
- <<chapter:configuration:connecting-to-the-host>>
- <<chapter:configuration:configuring-the-platform>>

****
'''

[[chapter:configuration:starting-the-platform-in-host-application]]
[discrete]
=== Starting the Platform in the Host Application

In the host application the SCION Microfrontend Platform is configured and web applications that want to interact with the platform are registered. For a detailed overview of platform and application configuration properties, refer to chapter <<chapter:configuration:configuring-the-platform>>.

The host application starts the platform by calling the `MicrofrontendPlatformHost.start` method.

[source,typescript]
----
include::starting-the-platform.snippets.ts[tags=startHost1]
----
<1> Lists the applications allowed to interact with the platform.

The platform should be started during the bootstrapping of the host application. In Angular, for example, the platform is typically started in an app initializer. Since starting the platform host may take some time, you should wait for the startup Promise to resolve before interacting with the platform.

The host application can provide a manifest to declare intentions and contribute behavior to integrated applications via `MicrofrontendPlatformConfig.host.manifest`. The manifest can be specified either as an object literal or as a URL to load it over the network.

[source,typescript]
----
include::starting-the-platform.snippets.ts[tags=startHost2]
----
<1> Specifies the host manifest. Alternatively, you can pass a URL to the manifest for loading it over the network.
<2> Lists the applications allowed to interact with the platform.

[[chapter:configuration:connecting-to-the-host]]
[discrete]
=== Connecting to the Platform from a Microfrontend

A microfrontend connects to the platform host by invoking the `connect` method on `MicrofrontendPlatformClient` and passing its application identity as the argument.

The following code snippet illustrates how to connect to the platform from a microfrontend.

[source,typescript]
----
include::starting-the-platform.snippets.ts[tags=connectToHost]
----

A microfrontend should connect to the platform host during application bootstrapping. In Angular, for example, this is typically done in an app initializer. Since connecting to the platform host is an asynchronous operation, the microfrontend should wait for the Promise to resolve before interacting with the platform or other microfrontends.

NOTE: The platform connects to the host through its window hierarchy. Therefore, the microfrontend must be embedded as direct or indirect child window of the host application window.

[[chapter:configuration:configuring-the-platform]]
[discrete]
=== Configuring the Platform
You configure the platform by passing a config object when starting the platform host. Besides listing micro applications allowed to interact with the platform, you can specify the manifest of the host application, control platform behavior, declare common properties available to micro applications, and more.

[[objects::microfrontend-platform-config]]
.Properties of `MicrofrontendPlatformConfig`
[cols="1,4,1,1,5"]
|===
| Property | Type | Mandatory | Default | Description

| applications
a| `<<objects::application-config,ApplicationConfig>>[]`
| yes
|
| Lists the applications allowed to interact with the platform.

See <<objects::application-config,ApplicationConfig>> for an overview of the properties.

| host
a| `<<objects::host-config,HostConfig>>`
| no
|
| Configures the interaction of the host application with the platform.

As with micro applications, you can provide a manifest for the host, allowing the host to contribute capabilities and declare intentions.

See <<objects::host-config,HostConfig>> for an overview of the properties.

| activatorApiDisabled
a| `boolean`
| no
a| `true`
| Controls whether the Activator API is enabled.

Activating the Activator API enables micro applications to contribute `activator` microfrontends. Activator microfrontends are loaded at platform startup for the entire lifecycle of the platform. An activator is a startup hook for micro applications to initialize or register message or intent handlers to provide functionality.

| [[objects::microfrontend-platform-config:manifestLoadTimeout]]manifestLoadTimeout
a| `number`
| no
|
| Maximum time (in milliseconds) that the platform waits until the manifest of an application is loaded.

You can set a different timeout per application via <<objects::application-config:manifestLoadTimeout,ApplicationConfig.manifestLoadTimeout>>. If not set, by default, the browser's HTTP fetch timeout applies.
Consider setting this timeout if, for example, a web application firewall delays the responses of unavailable applications.

| [[objects::microfrontend-platform-config:activatorLoadTimeout]] activatorLoadTimeout
a| `number`
| no
|
| Maximum time (in milliseconds) for each application to signal readiness.

If specified and activating an application takes longer, the host logs an error and continues startup. Has no effect for applications which provide no activator(s) or are not configured to signal readiness.
You can set a different timeout per application via <<objects::application-config:activatorLoadTimeout,ApplicationConfig.activatorLoadTimeout>>.

By default, no timeout is set, meaning that if an app fails to signal readiness, e.g., due to an error, that app would block the host startup process indefinitely. It is therefore recommended to specify a timeout accordingly.

| liveness
a| `<<objects::liveness-config,LivenessConfig>>`
| no
|
| Configures the liveness probe performed between host and clients to detect and dispose stale clients.

See <<objects::liveness-config,LivenessConfig>> for an overview of the properties.

| properties
a| `Dictionary`
| no
|
| Defines user-defined properties which can be read by micro applications via `PlatformPropertyService`.

|===

The `ApplicationConfig` object is used to describe a micro application to be registered as micro application. Registered micro applications can connect to the platform and interact with each other.

[[objects::application-config]]
.Properties of `ApplicationConfig`
[cols="1,3,1,1,5"]
|===
| Property | Type | Mandatory | Default | Description

| symbolicName
a| `string`
| yes
a|
| Unique symbolic name of this micro application.

The symbolic name must be unique and contain only lowercase alphanumeric characters and hyphens.

| manifestUrl
a| `string`
| yes
|
| URL to the application manifest.

See <<objects::manifest,Manifest>> for an overview of the properties of the manifest.

| secondaryOrigin
a| `string`
| no
|
| Specifies an additional origin (in addition to the origin of the application) from which the application is allowed to connect to the platform.

By default, if not set, the application is allowed to connect from the origin of the manifest URL or the base URL as specified in the manifest file. Setting an additional origin may be necessary if, for example, integrating microfrontends into a rich client, enabling an integrator to bridge messages between clients and host across browser boundaries.

| [[objects::application-config:manifestLoadTimeout]]manifestLoadTimeout
a| `number`
| no
|
| Maximum time (in milliseconds) that the host waits until the manifest for this application is loaded.

If set, overrides the global timeout as configured in <<objects::microfrontend-platform-config:manifestLoadTimeout,MicrofrontendPlatformConfig.manifestLoadTimeout>>.

| [[objects::application-config:activatorLoadTimeout]]activatorLoadTimeout
a| `number`
| no
|
| Maximum time (in milliseconds) for this application to signal readiness. If activating this application takes longer, the host logs an error and continues startup.

If set, overrides the global timeout as configured in <<objects::microfrontend-platform-config:activatorLoadTimeout,MicrofrontendPlatformConfig.activatorLoadTimeout>>.

| exclude
a| `boolean`
| no
a| `false`
| Excludes this micro application from registration, e.g. to not register it in a specific environment.

| scopeCheckDisabled
a| `boolean`
| no
a| `false`
| Controls whether this micro application can interact with private capabilities of other micro applications.

By default, scope check is enabled. Disabling scope check is strongly discouraged.

| intentionCheckDisabled
a| `boolean`
| no
a| `false`
| Controls whether this micro application can interact with the capabilities of other apps without having to declare respective intentions.

By default, intention check is enabled. Disabling intention check is strongly discouraged.

| intentionRegisterApiDisabled
a| `boolean`
| no
a| `true`
| Controls whether this micro application can register and unregister intentions dynamically at runtime.

By default, this API is disabled. Enabling this API is strongly discouraged.

|===

The `HostConfig` object is used to configure the interaction of the host application with the platform.

[[objects::host-config]]
.Properties of `HostConfig`
[cols="1,2,1,1,5"]
|===
| Property | Type | Mandatory | Default | Description

| symbolicName
a| `string`
| no
a| `host`
| Symbolic name of the host.

If not set, `host` is used as the symbolic name of the host. The symbolic name must be unique and contain only lowercase alphanumeric characters and hyphens.

| manifest
a| `string` \|
`<<objects::manifest,Manifest>>`
| no
|
| The manifest of the host.

The manifest can be passed either as an object literal or specified as a URL to be loaded over the network. Providing a manifest lets the host contribute capabilities or declare intentions.

See <<objects::manifest,Manifest>> for an overview of the properties of the manifest.

| scopeCheckDisabled
a| `boolean`
| no
a| `false`
| Controls whether the host can interact with private capabilities of other micro applications.

By default, scope check is enabled. Disabling scope check is strongly discouraged.

| intentionCheckDisabled
a| `boolean`
| no
a| `false`
| Controls whether the host can interact with the capabilities of other apps without having to declare respective intentions.

By default, intention check is enabled. Disabling intention check is strongly discouraged.

| intentionRegisterApiDisabled
a| `boolean`
| no
a| `true`
| Controls whether the host can register and unregister intentions dynamically at runtime.

By default, this API is disabled. Enabling this API is strongly discouraged.

| messageDeliveryTimeout
a| `number`
| no
a| `10'000ms`
| Maximum time (in milliseconds) that the platform waits to receive dispatch confirmation for messages sent by the host until rejecting the publishing Promise.

|===

The `LivenessConfig` object is used to configure the liveness probe performed between host and clients to detect and dispose stale clients. Clients not replying to the probe are removed.

[[objects::liveness-config]]
.Properties of `LivenessConfig`
[cols="1,2,1,3,5"]
|===
| Property | Type | Mandatory | Default | Description

| interval
a| `number`
| yes
a| `60s` (if no `LivenessConfig` is provided)
| Interval (in seconds) at which liveness probes are performed between host and connected clients.

Note that the interval must not be 0 and be greater than twice the timeout period to give a probe enough time to complete before performing a new probe.


| timeout
a| `number`
| yes
a| `10s` (if no `LivenessConfig` is provided)
| Timeout (in seconds) after which a client is unregistered if not replying to the probe.

Note that the timeout must not be 0 and be less than half the interval period to give a probe enough time to complete before performing a new probe.

|===
