:basedir: ../../..
include::{basedir}/_common.adoc[]

[[chapter:platform-lifecycle]]
== Platform Lifecycle

This chapter describes the lifecycle of the SCION Microfrontend Platform.

[.chapter-toc]
****
[.chapter-title]
In this Chapter

- <<chapter:platform-lifecycle:platform-lifecycle-states>>
- <<chapter:platform-lifecycle:platform-startup-runlevels>>
- <<chapter:platform-lifecycle:platform-startup-progress>>
- <<chapter:platform-lifecycle:platform-shutdown>>

****
'''

[[chapter:platform-lifecycle:platform-lifecycle-states]]
=== Platform Lifecycle States

The lifecycle of the SCION Microfrontend Platform is controlled by the class `MicrofrontendPlatform`, providing methods to start and stop the platform. During its lifecycle, it traverses different lifecycle states, as defined in the enumeration `PlatformState`.

Starting:: Indicates that the platform is about to start.
Started:: Indicates that the platform started.
Stopping:: Indicates that the platform is about to stop.
Stopped:: Indicates that the platform is not running.

You can register a listener that is called when the platform enters a state, as follows:

[source,typescript]
----
include::platform-lifecycle.snippets.ts[tags=platform-lifecycle:when-state]
----

Alternatively, a bean can implement the `PreDestroy` lifecycle hook to get notified when the platform is about to stop, as follows:

[source,typescript]
----
include::platform-lifecycle.snippets.ts[tags=platform-lifecycle:bean-pre-destroy-hook]
----

[[chapter:platform-lifecycle:platform-startup-runlevels]]
=== Platform Startup Runlevels

During the transition from the `Starting` to the `Started` platform state, the platform cycles through different runlevels for running initializers, enabling the controlled initialization of platform services. A runlevel is represented by a number greater than or equal to 0. Initializers can specify a runlevel in which to execute. Initializers bound to lower runlevels execute before initializers of higher runlevels. Initializers of the same runlevel may execute in parallel. The platform enters the state `Started` after all initializers have completed.

The platform defines the runlevels `0` to `3`, as follows:

Runlevel 0:: In runlevel 0, the platform host fetches manifests of registered micro applications.
Runlevel 1:: In runlevel 1, the platform constructs eager beans.
Runlevel 2:: From runlevel 2 and above, messaging is enabled. This is the default runlevel at which initializers execute if not specifying any runlevel.
Runlevel 3:: In runlevel 3, the platform host installs activator microfrontends.

To hook into the platform's startup process, you can register an initializer and bind it to a runlevel. You are not limited to the runlevels `0` to `3`. For example, to run an initializer after all other initializers have completed, register the initializer in runlevel `4` or higher.

The following code snippet illustrates how to register an initializer in runlevel 4:

[source,typescript]
----
include::platform-lifecycle.snippets.ts[tags=platform-lifecycle:registerInitializer]
----

[[chapter:platform-lifecycle:platform-startup-progress]]
=== Platform Startup Progress
Starting the platform can take some time, especially in the host, as the host loads the manifests of the registered applications, among other things, and waits for the applications to signal their readiness.

You can subscribe to the platform's startup progress to provide feedback to the user about the progress of the platform startup, e.g., in form of a progress bar or spinner.

The following code snippet illustrates how to subscribe to the startup progress:
[source,typescript]
----
include::platform-lifecycle.snippets.ts[tags=platform-lifecycle:startupProgress]
----

The platform tracks the progress of following activities:

Loading manifests:: Advances the progress after fetching the manifest of each registered application.
Loading activators:: Advances the progress after loading the activator(s) of each application.
Running initializers:: Advances the progress after the platform enters the `Started` state. Thus, initializers contribute to the overall progress.


[[chapter:platform-lifecycle:platform-shutdown]]
=== Platform Shutdown

When the platform is stopped, it first enters the `Stopping` platform state. In this state, the beans registered with the platform are destroyed. Beans are destroyed according to their destruction order as specified at bean registration. Beans of the same destroy order are destroyed in reverse construction order. Beans can implement the `PreDestroy` lifecycle hook to get notified when they are about to be destroyed.

The platform allows the application to send messages while the platform is stopping. After all beans are destroyed, the client is disconnected from the host and the platform enters the `Stopped` state.

By default, the platform initiates shutdown when the browser unloads the document, i.e., when `beforeunload` is triggered. The main reason for `beforeunload` instead of `unload` is to avoid posting messages to disposed windows. However, if `beforeunload` is not triggered, e.g., when an iframe is removed, we fall back to `unload`.

You can change this behavior by registering a custom `MicrofrontendPlatformStopper` bean, as follows:

[source,typescript]
----
include::platform-lifecycle.snippets.ts[tags=platform-lifecycle:microfrontend-platform-stopper]
----
