:basedir: ../../..
include::{basedir}/_common.adoc[]

[[chapter:intent-based-messaging]]
== Intent-Based Messaging
This chapter introduces the intent-based communication for controlled collaboration between micro applications.
[.chapter-toc]
****
[.chapter-title]
In this Chapter

- <<chapter:intent-based-messaging:what-is-intent-based-messaging>>
- <<chapter:intent-based-messaging:declaring-intention>>
- <<chapter:intent-based-messaging:publishing-intent>>
- <<chapter:intent-based-messaging:publishing-retained-intent>>
- <<chapter:intent-based-messaging:declaring-capability>>
- <<chapter:intent-based-messaging:receiving-intents>>
- <<chapter:intent-based-messaging:request-response-message-exchange-pattern>>
- <<chapter:intent-based-messaging:convenience-api-for-handling-intents>>
****
'''

[[chapter:intent-based-messaging:what-is-intent-based-messaging]]
[discrete]
=== What is Intent-Based Messaging?
Intent-based messaging enables controlled collaboration between micro applications, a mechanism known from Android development where an application can start an activity via an _Intent_ (such as sending an email).

This kind of communication is similar to the <<chapter:topic-based-messaging,topic-based>> communication, thus implements also the publish-subscribe messaging pattern. Both communication models allow messages to be sent between instances of applications. However, intent-based messaging goes beyond "simple" messaging and is the basis for controlled collaboration. Controlled collaboration means that communication flows are explicit and must be declared in the manifest. For the sending application, this means it must declare an intention in its manifest, and for the receiving application, it must provide a capability. The declaration of capabilities in the manifest file is similar to the OpenAPI specification for REST APIs - it defines the contract for the provided interaction.

NOTE: We recommend using intent-based communication for cross-application communication to make interaction flows explicit.

The advantage of this kind of communication becomes apparent when the number of cross-application communications grows to provide an overview of the communication flows in the system. For example, in case of a breaking change in the message format, you can clearly identify your communication peers to coordinate the migration. Further, a capability is more than "simply" a messaging endpoint. A capability can be thought of as an API that can be invoked via intent, browsed via the DevTools or programmatically via the <<chapter:intention-api>>. A capability can specify parameters which must be passed along with the intent. Parameters are part of the contract between the intent publisher and the capability provider.

In topic-based communication, messages are published to a topic destination. In intent-based communication, on the other hand, the destination are capabilities, formulated in an abstract way, consisting of a a _type_, and optionally a _qualifier_. The _type_ categorizes a capability in terms of its functional semantics. A capability may also define a _qualifier_ to differentiate the different capabilities of the same type. The _type_ is a string literal and the qualifier a dictionary of key-value pairs. To better understand the concept of the qualifier, a bean manager can be used as an analogy. If there is more than one bean of the same type, a qualifier can be used to control which bean to inject.

The terminology and concepts are explained in more detail in the <<chapter:intention-api>> chapter. This chapter focuses on communication and illustrates how to send and receive intents using the link:{typedoc-url}/classes/IntentClient.html[IntentClient, window=\"_blank\"], which is available from the Platform's <<terminology:bean-manager,bean manager>>.

[[chapter:intent-based-messaging:declaring-intention]]
[discrete]
=== Declaring an Intention
An application must declare an intention in its manifest in order to interact with a capability.

To illustrate the concept of intent-based messaging, we will look at an IoT example with sensors controlling room temperature modeled as capabilities. To set the temperature of a room, we send an intent to the room sensor. To get the room temperature, we query the sensor using request-response.

[source,json]
----
include::intent-based-messaging.snippets.ts[tags=intention-declaration]
----
<1> Declares the intention to interact with the temperature sensor in the kitchen.
+
The _type_ of the intention must exactly match the type of the capability we want to interact with. In specifying the qualifier, we are more flexible. For instance, we can use wildcards to match multiple capabilities with a single intention declaration. +

NOTE: A micro application is implicitly qualified to interact with all its capabilities without declaring an intention.

TIP: Using the asterisk wildcard (`*`) in the qualifier allows matching multiple capabilities with a single intention declaration.

To learn more about an intention, see chapter <<chapter:intention-api:intention>> in <<chapter:intention-api>>.

[[chapter:intent-based-messaging:publishing-intent]]
[discrete]
=== Publishing an Intent
An application can publish intents for intentions declared in its manifest. The platform transports the intent to applications that provide a fulfilling capability. Along with the intent, the application can pass transfer data, either as payload, message headers or parameters. Passed data must be serializable with the _Structured Clone Algorithm_.

In the following example, we send an intent to the temperature sensor in the kitchen to set the temperature to 22°C.

[source,typescript]
----
include::intent-based-messaging.snippets.ts[tags=publish-intent]
----
<1> Constructs the intent to interact with the temperature sensor in the kitchen.
<2> Publishes the intent via `IntentClient`, obtained from the bean manager.

NOTE: The method to publish an intent returns a Promise that resolves when dispatched the intent, or that rejects if the message broker rejected the intent.

To learn more about an intent, see chapter <<chapter:intention-api:intent>> in <<chapter:intention-api>>.

[[chapter:intent-based-messaging:publishing-retained-intent]]
[discrete]
=== Publishing a Retained Intent
The platform supports publishing an intent as a _retained_ intent. Retained intents help newly subscribed clients to get the last intent published for a capability immediately upon subscription. The broker stores one retained intent per capability, i.e., a later sent retained intent will replace a previously sent retained intent. To delete a retained intent, send a retained intent without payload to the same destination. Deletion intents are not transported to subscribers.

In the following example, we set the kitchen temperature to 22°C. We send a retained intent since the kitchen temperature sensor may not be available yet. As soon as it connects to the platform, it will receive the intent for adjusting the temperature.

[source,typescript]
----
include::intent-based-messaging.snippets.ts[tags=publish-retained-intent]
----
<1> Sets the `retain` flag to `true`, instructing the message broker to store this intent as a retained intent.

[[chapter:intent-based-messaging:declaring-capability]]
[discrete]
=== Declaring a Capability
An application can make functionality available to other applications via capabilities. Typically, capabilities are declared in the manifest, but can also be contributed programmatically using the `ManifestService`.

The following code snippet illustrates the declaration of the kitchen temperature sensor as a capability in the manifest.

[source,json]
----
include::intent-based-messaging.snippets.ts[tags=capability-declaration]
----
<1> Describes the capability.
<2> Categorizes the capability to be a `temperature` sensor.
+
The platform provides some platform-specific capability types like `Activator` or `Microfrontend`. For custom capabilities, you can choose any name.
<3> Qualifies the capability if having multiple `temperature` sensor capabilities.
<4> Makes this a public capability so that other applications can interact with the kitchen sensor.

TIP: To have consistency among the qualifiers in the <<terminology:application,application>>, we recommend defining guidelines how to name qualifier entries.

To learn more about a capability, see chapter <<chapter:intention-api:capability>> in <<chapter:intention-api>>.

[[chapter:intent-based-messaging:receiving-intents]]
[discrete]
=== Receiving Intents
Intents are transported to applications that provide a fulfilling capability and are typically subscribed to in an activator. An activator is a special microfrontend that an application can provide. Activators are loaded when starting the host application and run for the entire application lifecycle. An activator microfrontend is special in that it is never displayed to the user. Learn more about activator in the chapter <<chapter:activator>>.

The following code snippet illustrates how to receive intents.

[source,typescript]
----
include::intent-based-messaging.snippets.ts[tags=handle-intent]
----
<1> Defines the selector to filter intents. Without a selector, you would receive all intents you have defined a capability for. The selector supports the use of wildcards in the qualifier.
<2> Subscribes to intents that match the selector.

IMPORTANT: An application only receives intents for which it provides a fulfilling capability. The selector is used as a filter only.

[[chapter:intent-based-messaging:request-response-message-exchange-pattern]]
[discrete]
=== Request-Response Message Exchange
The platform facilitates the _request-response_ message exchange pattern for synchronous communication.

The communication is initiated by the requestor by sending a request. The recipient can then respond to the request. Just as in JMS (_Java Message Service_), the platform sets a `ReplyTo` message header on the intent, which contains the topic of a temporary inbox where the replier can send replies to. The inbox is destroyed when the requestor unsubscribes.

The following code snippet illustrates how to initiate a _request-response_ communication via intent-based messaging and receiving replies. To explain this type of communication, let's take a client that requests the current kitchen temperature.

[source,typescript]
----
include::intent-based-messaging.snippets.ts[tags=request]
----
<1> Initiates a _request-response_ communication by invoking the `request$` method on the `IntentClient`.
<2> Prints the received temperature to the console.

[NOTE]
====
In request-response communication, by default, the requestor’s Observable never completes. However, the replier can include the response status code in the reply’s headers, allowing to control the lifecycle of the requestor’s Observable. For example, the status code `250` `ResponseStatusCodes.TERMINAL` allows completing the requestor’s Observable after emitted the reply, or the status code `500` `ResponseStatusCodes.ERROR` to error the Observable. See the enum `ResponseStatusCodes` for available status codes.

If the replier does not complete the communication, the requestor can use the `take(1)` RxJS operator to unsubscribe upon the receipt of the first reply.

Note that the platform evaluates status codes only in request-response communication. They are ignored when observing topics or intents in pub/sub communication.
====

'''

The following code snippet shows how requests (intents) are received and answered. You can reply to an intent by sending one or more replies to the `replyTo` topic contained in the intent's headers. Please note to send replies via the `MessageClient`.

_For illustration purposes, for each request, the following example subscribes to the temperature sensor. The sensor observable never completes and continuously emits when the temperature changes._

[source,typescript]
----
include::intent-based-messaging.snippets.ts[tags=reply]
----
<1> Reads the `ReplyTo` topic from the request where to send replies to.
<2> Sends the current kitchen temperature to the requestor.
<3> Stops replying when the requestor unsubscribes.
<4> Sets a message header to immediately complete the requestor's Observable after emitted the reply.

TIP: If streaming data like in the example above, the replier can use the RxJS `takeUntilUnsubscribe` operator of the platform to stop replying when the requestor unsubscribes.

[[chapter:intent-based-messaging:convenience-api-for-handling-intents]]
[discrete]
=== Convenience API for handling messages
The intent client provides the `onIntent` method as a convenience to the `observe$` method. Unlike `observe$`, intents are passed to a callback function rather than emitted from an Observable. Response(s) can be returned directly from the callback. It supports error propagation and request termination. Using this method over `observe$` significantly reduces the code required to respond to requests.

[source,typescript]
----
include::intent-based-messaging.snippets.ts[tags=onIntent]
----

For each intent received, the specified callback function is called. When used in request-response communication, the callback function can return the response either directly or in the form of a Promise or Observable. Returning a Promise allows the response to be computed asynchronously, and an Observable allows to return one or more responses, e.g., for streaming data. In either case, when the final response is produced, the handler terminates the communication, completing the requestor's Observable. If the callback throws an error, or the returned Promise or Observable errors, the error is transported to the requestor, erroring the requestor's Observable.

