:basedir: ../..
include::{basedir}/_common.adoc[]

[[chapter:terminology]]
== Terminology

[#terminology:activator]
Activator::
An activator is a startup hook for micro applications to initialize or register message or intent handlers to provide functionality. Activator microfrontends are loaded at platform startup for the entire lifecycle of the platform
+
In the broadest sense, an activator is a kind of <<terminology:microfrontend,microfrontend>>, i.e. an HTML page that runs in an iframe. In contrast to regular <<terminology:microfrontend,microfrontends>>, however, at platform startup, the <<terminology:platform,platform>> loads activator microfrontends into hidden iframes for the entire platform lifecycle, thus, providing a stateful session to the <<terminology:micro-application,micro application>> on the client-side.

[#terminology:application]
Application::
This term is used throughout this guide to refer to the entire application as presented to the user.

[#terminology:bean-manager]
Bean Manager::
The bean manager is the central point to get references to platform services, such as the `MessageClient`, `IntentClient` or `OutletRouter`. The bean manager is provided by `@scion/toolkit` NPM package.

[#terminology:capability]
Capability::
The term `capability` refers to the <<terminology:intention-api,Intention API>> of the SCION Microfrontend Platform.
+
A capability represents some functionality of a <<terminology:micro-application,micro application>> that is available to qualified micro applications through the <<terminology:intention-api,Intention API>>. A micro application declares its capabilities in its <<terminology:manifest,manifest>>. Qualified micro applications can browse capabilities similar to a catalog, or interact with capabilities via <<terminology:intent,intent>>.
+
A capability is formulated in an abstract way consisting of a _type_ and optionally a _qualifier_. The _type_ categorizes a capability in terms of its functional semantics (e.g., `microfrontend` if providing a microfrontend). Multiple capabilities can be of the same _type_. In addition to the _type_, a capability can define a <<terminology:qualifier,qualifier>> to differentiate the different capabilities of the same _type_.
+
A capability can have private or public visibility. If private, the capability is not visible to other micro applications.
+
A capability can specify parameters which the intent issuer can/must pass along with the intent. Parameters are part of the contract between the intent publisher and the capability provider. They do not affect the intent routing, unlike the qualifier.

[#terminology:cross-origin-messaging]
Cross-Origin Messaging::
Cross-origin messaging means the communication between web content loaded from different <<terminology:origin,origins>>.

[#terminology:host-app]
Host Application::
+
include::{terminologydir}/host-application.adoc[]
+
The host app starts the <<terminology:platform,platform>> host and registers <<terminology:micro-application,micro applications>>. As with micro applications, the host can provide a manifest to interact with other micro applications and contribute behavior in the form of <<terminology:capability,capabilities>>.

[#terminology:intent]
Intent::
The term `intent` refers to the <<terminology:intention-api,Intention API>> of the SCION Microfrontend Platform.
+
The intent is the message that a <<terminology:micro-application,micro application>> sends to interact with functionality that is available in the form of a <<terminology:capability,capability>>.
+
The platform transports the intent to the <<terminology:micro-application,micro applications>> that provide the requested <<terminology:capability,capability>>. A micro application can issue an intent only if having declared an <<terminology:intention,intention>> in its <<terminology:manifest,manifest>>. Otherwise, the platform rejects the intent.
+
An intent is formulated in an abstract way, having assigned a _type_, and optionally a <<terminology:qualifier,qualifier>>. This information is used for resolving the capability; thus, it can be thought of as a form of capability addressing. See the definition of a <<terminology:capability,capability>> for more information.

[#terminology:intention]
Intention::
The term `intention` refers to the <<terminology:intention-api,Intention API>> of the SCION Microfrontend Platform.
+
An intention refers to one or more <<terminology:capability,capabilities>> that a <<terminology:micro-application,micro application>> wants to interact with. Manifesting intentions enables us to see dependencies between applications down to the functional level.
+
Intentions are declared in the application's <<terminology:manifest,manifest>> and are formulated in an abstract way, consisting of a _type_ and optionally a qualifier. The qualifier is used to differentiate capabilities of the same type.

[#terminology:intention-api]
Intention API::
The Intention API enables controlled collaboration between <<terminology:micro-application,micro applications>>. It is inspired by the Android platform where an application can start an activity via an _Intent_ (such as sending an email).
+
To collaborate, an application must express an <<terminology:intention,intention>>. An intention refers to one or more <<terminology:capability,capabilities>>, or activity, in the Android platform. Capabilities can be browsed similar to a catalog and invoked by issuing an <<terminology:intent,intent>>. Manifesting intentions enables us to see dependencies between applications down to the functional level.

[#terminology:manifest]
Manifest::
The manifest is a special file that contains information about a <<terminology:micro-application,micro application>>.
+
A micro application declares its <<terminology:intention,intentions>> and <<terminology:capability,capabilities>> in its manifest file. The manifest needs to be registered in the <<terminology:host-app,host application>>.

[#terminology:micro-application]
Micro Application::
+
include::micro-application.adoc[]
+
// this comment is necessary for the below terminology:microfrontend anchor to work

[#terminology:microfrontend]
Microfrontend::
+
include::microfrontend.adoc[]
+
// this comment is necessary for the below terminology:origin anchor to work

[#terminology:origin]
Origin::
The origin is defined by the scheme (protocol), host (domain), and port. Two objects have the same origin only when the scheme, host, and port all match.

[#terminology:platform]
Platform::
SCION Microfrontend Platform is a TypeScript-based open source library that enables the implementation of a framework-agnostic <<chapter:microfrontend-architecture,microfrontend architecture>> using iframes.
+
The platform provides fundamental building blocks for implementing a microfrontend architecture. These include <<chapter:cross-application-communication,cross-microfrontend communication>>, <<chapter:router-outlet,embedding of microfrontends>>, and <<chapter:routing,routing between microfrontends>>. SCION Microfrontend Platform is a lightweight, web stack agnostic library but not a framework. It has no user-facing components, and does not dictate any form of application structure.
+
Refer to chapter <<chapter:scion-microfrontend-platform>> for more information about the platform.

[#terminology:pub-sub]
Publish/Subscribe::
The publish/subscribe pattern (also known as pub/sub) decouples the client that sends a message (the publisher) from the client or clients that receive the message (the subscribers). Clients do not know about each other. A broker dispatches the messages to interested (subscribed) clients.

[#terminology:qualifier]
Qualifier::
The qualifier is a dictionary of arbitrary key-value pairs to differentiate <<terminology:capability,capabilities>> of the same _type_.
+
To better understand the concept of the qualifier, a bean manager can be used as an analogy. If there is more than one bean of the same type, a qualifier can be used to control which bean to inject.

[#terminology:router]
Router::
Allows controlling the content displayed in a <<terminology:router-outlet,router outlet>>. Routing works across <<terminology:microfrontend,microfrontend>> and <<terminology:micro-application,micro application>> boundaries, allowing the URL of an outlet to be set from anywhere in the  <<terminology:application,application>>.

[#terminology:router-outlet]
Router Outlet::
Web component for embedding web content using the <<terminology:router,router>>. The outlet uses an iframe to achieve the highest possible level of isolation via a separate browsing context. The URL is set indirectly via the <<terminology:router,router>>, allowing to control the outlet content from anywhere in the <<terminology:application,application>>.

[#terminology:same-origin-policy]
Same-Origin Policy::
The same-origin policy is a critical security mechanism that restricts how a document or script loaded from one origin can interact with a resource from another origin.

