:basedir: ../../..

[[chapter:platform-startup-progress]]
== Platform Startup Progress
Starting the platform can take some time, especially in the host, as the host loads the manifests of the registered applications, among other things, and waits for the applications to signal their readiness.

You can subscribe to the platform's startup progress to provide feedback to the user about the progress of the platform startup, e.g., in form of a progress bar or spinner.

The following code snippet illustrates how to subscribe to the startup progress:
[source,typescript]
----
include::platform-startup-progress.snippets.ts[tags=platform-lifecycle:startupProgress]
----

The platform tracks the progress of following activities:

Loading manifests:: Advances the progress after fetching the manifest of each registered application.
Loading activators:: Advances the progress after loading the activator(s) of each application.
Running initializers:: Advances the progress after the platform enters the `Started` state. Thus, initializers contribute to the overall progress.

