:basedir: ../../..
include::{basedir}/_common.adoc[]

[[chapter:platform-configuration]]
== Platform Configuration
This chapter explains how to configure micro applications in the host application.

[.chapter-toc]
****
[.chapter-title]
In this Chapter

- <<chapter:platform-configuration:introduction>>
- <<chapter:platform-configuration:configuring-micro-applications>>
- <<chapter:platform-configuration:configuring-micro-applications-and-platform>>
- <<chapter:platform-configuration:configuring-micro-applications-and-platform-asynchronously>>
- <<chapter:platform-configuration:enabling-plaform-features>>

****
'''

[[chapter:platform-configuration:introduction]]
[discrete]
=== Introduction
When bootstrapping the host application, you need to start the SCION Microfrontend Platform and provide the platform configuration. The config contains a list of web applications, so-called micro applications, and optionally some user-defined properties and platform flags.

You can pass the configuration either directly when starting the platform, or load it asynchronously using a config loader, e.g., for loading the config over the network.

[[chapter:platform-configuration:configuring-micro-applications]]
[discrete]
=== Configuring Micro Applications
For a web application to interact with the platform, you need to register it as a micro application. For each web app to register, you pass an `ApplicationConfig` to the platform, containing its name, manifest location, and privileges.

The following code snippet starts the platform and registers four micro applications.

[source,typescript]
----
include::platform-configuration.snippets.ts[tags=provide-app-array]
----
<1> Starts the platform in the host application.
<2> Registers the _product-catalog-app_ as micro application.
<3> Registers the _shopping-cart-app_ as micro application.
<4> Registers the _checkout-app_ as micro application.
<5> Registers the _customer-review-app_ as micro application.

As you can see, each web app needs to provide a manifest file which to register in the host application. The `ApplicationConfig` object supports the following properties.

[[chapter:platform-configuration:application-config]]
.Properties of `ApplicationConfig`
[cols="1,1,1,99"]
|===
| Property | Type | Mandatory | Description

| symbolicName
a| `string`
| yes
| Unique symbolic name of this micro application. Choose a short, lowercase name which contains alphanumeric characters and optionally dash characters.

| manifestUrl
a| `string`
| yes
| URL to the application manifest.

| exclude
a| `boolean`
| no
| Excludes this micro application from registration, e.g. to not register it in a specific environment.

| scopeCheckDisabled
a| `boolean`
| no
| Sets whether or not this micro application can issue intents to private capabilities of other apps. +
By default, scope check is enabled. Disabling scope check is discouraged.

| intentionCheckDisabled
a| `boolean`
| no
| Sets whether or not this micro application can look up intentions or issue intents for which it has not declared a respective intention. +
By default, intention check is enabled. Disabling intention check is strongly discouraged.

| intentionRegisterApiDisabled
a| `boolean`
| no
| Sets whether or not the API to manage intentions is disabled for this micro application. +
By default, this API is disabled. With this API enabled, the application can register and unregister intentions dynamically at runtime. Enabling this API is strongly discouraged.

|===

[[chapter:platform-configuration:configuring-micro-applications-and-platform]]
[discrete]
=== Configuring Micro Applications and the Platform
Instead of providing a list of application configs, you can alternatively pass a `PlatformConfig`. It additionally allows you to enable or disable platform flags and to add user-defined properties. User-defined properties are then also available in micro applications.

The following code snippet starts the platform and sets the two user-defined properties `auth` and `languages`.

[source,typescript]
----
include::platform-configuration.snippets.ts[tags=provide-platform-config]
----
<1> In the `properties` section you can define user-defined properties in the form of a dictionary with key-value pairs.

User-defined properties are available in micro applications via `PlatformPropertyService`. The following code snippet illustrates how to read platform properties in a micro application.

[source,typescript]
----
include::platform-configuration.snippets.ts[tags=read-platform-properties]
----
<1> Reads all user-defined properties.
<2> Reads a specific user-defined property.

The `PlatformConfig` object supports the following properties:

.Properties of `PlatformConfig`
[cols="1,1,1,99"]
|===
| Property | Type | Mandatory | Description

| apps
a| `Array<ApplicationConfig>`
| yes
| Defines the micro applications running in the platform. See <<chapter:platform-configuration:application-config,ApplicationConfig>> for more information.

| properties
a| `Dictionary`
| no
| Defines user-defined properties which can be read by micro applications via `PlatformPropertyService`.

| platformFlags
a| `PlatformFlags`
| no
| Platform flags are settings and features that you can enable to change how the platform works. See <<chapter:platform-configuration:platform-flags,PlatformFlags>> for more information.

|===

[[chapter:platform-configuration:configuring-micro-applications-and-platform-asynchronously]]
[discrete]
=== Configuring Micro Applications and the Platform Asynchronously

If you are looking for a more flexible way of registering the micro applications, you can alternatively provide a `PlatformConfigLoader`. The `PlatformConfigLoader` allows loading the `PlatformConfig` asynchronously, e.g., over the network.

The following code snippet implements a loader to fetch the platform config over the network.

[source,typescript]
----
include::platform-configuration.snippets.ts[tags=create-platform-config-loader]
----

When starting the platform, you pass the `class` symbol of your loader instead of the platform config object, as shown in the following example.

[source,typescript]
----
include::platform-configuration.snippets.ts[tags=provide-platform-config-loader]
----

[[chapter:platform-configuration:enabling-plaform-features]]
[discrete]
=== Enabling Platform Features
Platform flags are settings and features that you can enable to change how the platform works. You can set platform flags via the `PlatformConfig` object when starting the platform in the host application.

[[chapter:platform-configuration:platform-flags]]
.Properties of `PlatformFlags`
[cols="1,1,1,99"]
|===
| Property | Type | Mandatory | Description

| activatorApiDisabled
a| `boolean`
| no
| Sets whether or not the API to provide application activators is disabled. By default, this API is enabled.

|===

