/*
 * Copyright (c) 2018-2020 Swiss Federal Railways
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

/******************************************************************************************************************************************
 * ## NOTE ABOUT PROJECT-SPECIFIC CUSTOMIZATIONS
 *
 * - We do not activate `zone.js` nor Angular Testbed as SCION Microfrontend Platform is framework-agnostic.
 *   - Importing the module 'zone.js' activates zone.js, so we omit it.
 *   - Importing the module '@angular/core/testing' installs Angular test hooks for resetting the fake async zone, which, if missing zone.js, causes
 *     the following error since Angular 12:
 *     `zone-testing.js is needed for the fakeAsync() test helper but could not be found. Please make sure that your environment includes zone.js/testing`
 *   - If not having any sort of top-level import or export statement, the compiler complains with the following error: `Cannot redeclare block-scoped variable 'require'`.
 *     To fix this problem, we add an empty export to pretend to be a module, as following: `export {};`
 *     > For more information about this 'empty export' workaround, see https://medium.com/@muravitskiy.mail/cannot-redeclare-block-scoped-variable-varname-how-to-fix-b1c3d9cc8206
 *     > For more information about the webpack 'refer' keyword, see to https://stackoverflow.com/a/54066904
 * - We create a custom Webpack context if running in an iframe of {@link MicrofrontendFixture}.
 *
 * Please note when writing tests:
 * - To simulate asynchronous passage of time, use Jasmine clock instead of Angular fakeAsync zone (tick, flush).
 ******************************************************************************************************************************************/

// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import {WEBPACK_SCRIPT_CONTEXT, WEBPACK_SCRIPT_CONTEXT_ACTIVE} from './lib/testing/microfrontend-fixture/microfrontend-fixture';
// import 'zone.js';
// import 'zone.js/testing';
// import {getTestBed} from '@angular/core/testing';
// import {BrowserDynamicTestingModule, platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';
export {};

declare const require: {
  context(path: string, deep?: boolean, filter?: RegExp): {
    <T>(id: string): T;
    keys(): string[];
  };
};

// First, initialize the Angular testing environment.
// getTestBed().initTestEnvironment(
//   BrowserDynamicTestingModule,
//   platformBrowserDynamicTesting(),
// );

// Then we find all the tests.
const context = createWebpackContext();
// And load the modules.
context.keys().forEach(context);

/**
 * Creates the Webpack context as follows:
 *
 * - if running specs, creates a Webpack context of only "*.spec.ts" files (plus referenced files) (as generated by Angular CLI)
 * - if running in an iframe of {@link MicrofrontendFixture}, creates a webpack context of only "*.script.ts" files (plus referenced files)
 *
 * See https://webpack.js.org/guides/dependency-management/#requirecontext for more information about the Webpack context.
 *
 * Related files:
 * - projects/scion/microfrontend-platform/tsconfig.lib.json
 * - projects/scion/microfrontend-platform/tsconfig.spec.json
 * - projects/scion/microfrontend-platform/src/lib/testing/microfrontend-fixture/microfrontend-fixture.ts
 */
function createWebpackContext(): any {
  if (window[WEBPACK_SCRIPT_CONTEXT_ACTIVE]) {
    const webpackContext = require.context('./', true, /\.script\.ts$/);
    window[WEBPACK_SCRIPT_CONTEXT] = webpackContext;
    return webpackContext;
  }
  else {
    return require.context('./', true, /\.spec\.ts$/);
  }
}
