:basedir: ../../..
include::{basedir}/_common.adoc[]

[[chapter:intention-api]]
== Intention API
This chapter introduces the concepts of the Intention API.

[.chapter-toc]
****
[.chapter-title]
In this Chapter

- <<chapter:intention-api:concepts-and-usage>>
- <<chapter:intention-api:manifest>>
- <<chapter:intention-api:capability>>
- <<chapter:intention-api:intention>>
- <<chapter:intention-api:intent>>
- <<chapter:intention-api:capability-lookup>>
- <<chapter:intention-api:intention-lookup>>
- <<chapter:intention-api:capability-registration>>
- <<chapter:intention-api:intention-registration>>
- <<chapter:intention-api:capability-interception>>

****
'''

[[chapter:intention-api:concepts-and-usage]]
=== Concepts and Usage
The Intention API enables controlled collaboration between micro applications. It is inspired by the Android platform where an application can start an activity via an _Intent_ (such as sending an email).

To collaborate, an application must express an <<terminology:intention,intention>>. An intention refers to one or more <<terminology:capability,capabilities>>, or activity, in the Android platform. Capabilities can be browsed similar to a catalog and invoked by issuing an <<terminology:intent,intent>>. Manifesting intentions enables us to see dependencies between applications down to the functional level.

====
A micro application can make functionality available to micro applications in the form of capabilities. For a micro application to browse or invoke a capability, the micro application must declare an intention in its manifest. To invoke a capability, a micro application issues an intent.

[.text-center]
image::intention-api.svg[]
====

Both capabilities and intentions need to be declared in the manifest. For example, capabilities can be browsed to create dynamic page content, such as a toolbar with items contributed via capabilities. When the user clicks an item of the toolbar, the application can issue an intent, which the platform transports to the application providing the capability.

[[chapter:intention-api:manifest]]
=== The Manifest
The manifest is a special file that contains information about a micro application. A micro application declares its intentions and capabilities in its manifest file. The manifest needs to be registered in the host application via URL.

The following code snippet shows the manifest of the _Product Catalog Application_.

[source,json]
----
include::intention-api.snippets.ts[tags=manifest]
----

[[objects::manifest]]
.Properties of `Manifest`
[cols="1,2,1,5"]
|===
| Property | Type | Mandatory | Description

| name
a| `string`
| yes
| The name of the application, e.g. displayed in the Developer Tools.

| baseUrl
a| `string`
| no
| URL to the application root. The URL can be fully qualified, or a path relative to the origin under which serving the manifest file. If not specified, the origin of the manifest file acts as the base URL. The platform uses the base URL to resolve microfrontends such as activator endpoints. +
For a _Single Page Application_ that uses _hash-based_ routing, you typically specify the hash symbol (`#`) as the base URL.

| capabilities
a| `<<objects::capability,Capability>>[]`
| no
| Functionality that qualified micro application can look up or call via intent.

| intentions
a| `<<objects::intention,Intention>>[]`
| no
| Functionality which this micro application intends to use.
|===

[[chapter:intention-api:capability]]
=== What is a Capability?
A capability can be thought of as an API that an application provides that can be invoked via intent, browsed via the DevTools or programmatically via the Intention API. Capabilities must be registered in the manifest or contributed programmatically via `ManifestService`.

A capability is formulated in an abstract way consisting of a _type_ and optionally a _qualifier_. The _type_ categorizes a capability in terms of its functional semantics (e.g., `microfrontend` if providing a microfrontend). Multiple capabilities can be of the same _type_. In addition to the _type_, a capability can define a qualifier to differentiate the different capabilities of the same _type_. A qualifier is a dictionary of arbitrary key-value pairs.

TIP: Data ownership is an important rule to follow when implementing a microservices/microfrontend architecture. Therefore, adding the domain entity name to the qualifier is an easy way to uniquely address capabilities.

TIP: To have consistency among the qualifiers in the entire <<terminology:application,application>>, we recommend defining guidelines how to name qualifier entries.

A capability can have _private_ or _public_ visibility. If _private_, which is by default, the capability is not visible to other micro applications; thus, it can only be invoked or browsed by the providing micro application.

A capability can specify parameters which the intent issuer can/must pass along with the intent. Parameters are part of the contract between the intent publisher and the capability provider. They do not affect the intent routing, unlike the qualifier.

Metadata can be associated with a capability in its `properties` section. For example, if providing a microfrontend, the URL to the microfrontend can be added as property, or if the capability contributes a toolbar item, its label to be displayed.

The following code snippet shows an example of how to declare a capability in the manifest of an application.

[source,json]
----
include::intention-api.snippets.ts[tags=capability-declaration]
----

[[objects::capability]]
.Properties of `Capability`
[cols="1,2,1,5"]
|===
| Property | Type | Mandatory | Description

| type
a| `string`
| yes
| Categorizes the capability in terms of its functional semantics (e.g., `microfrontend` if providing a microfrontend). There are a handful of platform-specific capability types, such as `activator` or `microfrontend`. For custom capabilities, you can choose any name.

| qualifier
a| `Dictionary`
| no
a|
The qualifier is a dictionary of key-value pairs to differentiate capabilities of the same _type_. The qualifier is like an abstract description of the capability. It should include enough information to uniquely identify the capability.

Intents must exactly match the qualifier of the capability, if any.

| params
a| `ParamDefinition[]`
| no
a|
Specifies parameters which the intent issuer can/must pass along with the intent.

Parameters are part of the contract between the intent publisher and the capability provider. They do not affect the intent routing, unlike the qualifier.
A parameter needs to declare its name and whether it is required or optional, as follows: `{"name":"param","required": true}`. Optionally, a description, default value and deprecation notes can be specified, or additional metadata to be interpreted in an interceptor.

| private
a| `boolean`
| no
a| Controls whether this capability is private. Defaults to `true`.

If private, the capability is not visible to other applications and can only be accessed by the providing application.

Note: Applications configured with `scopeCheckDisabled` can still access private capabilities (discouraged).

| inactive
a| `boolean`
| no
a| Controls whether this capability is inactive. Defaults to `false`.

Capabilities can be marked as inactive in a capability interceptor, for example, based on user permissions. Inactive capabilities are unavailable to applications but still visible in the SCION DevTools for discovery.

Note: Applications configured with `capabilityActiveCheckDisabled` can still access inactive capabilities (discouraged).

| description
a| `string`
| no
| A short description to explain the capability.

| properties
a| `Dictionary`
| no
| Arbitrary metadata to be associated with the capability.
|===

In addition to declaring a capability in the manifest, the micro application typically subscribes to intents in an activator. Refer to chapter <<chapter:activator>> for more information.

The following code snippet shows an example of how an application can subscribe to intents.

[source,typescript]
----
include::intention-api.snippets.ts[tags=intent-handling]
----

IMPORTANT: A micro application only receives intents for which it provides a fulfilling capability. The selector is used as a filter only.

For more information about handling an intent, see the chapter <<chapter:intent-based-messaging:receiving-intents>> in <<chapter:intent-based-messaging>>.

[[chapter:intention-api:intention]]
=== What is an Intention?
An intention refers to one or more capabilities that an application wants to interact with. Intentions are declared in the application's manifest and are formulated in an abstract way, consisting of a _type_ and optionally a qualifier. The qualifier is used to differentiate capabilities of the same type.

NOTE: If providing a capability, the providing application is implicitly qualified to interact with its capability, thus needs not to declare an intention.

The following code snippet shows an example of how to declare an intention in the manifest of an application.

[source,json]
----
include::intention-api.snippets.ts[tags=intention-declaration]
----

[[objects::intention]]
.Properties of `Intention`
[cols="1,2,1,5"]
|===
| Property | Type | Mandatory | Description

| type
a| `string`
| yes
| The type of capability to interact with.

| qualifier
a| `Dictionary`
| no
a|
Qualifies the capability which to interact with.

The qualifier is a dictionary of arbitrary key-value pairs to differentiate capabilities of the same _type_.

The intention must exactly match the qualifier of the capability, if any. The intention qualifier allows using wildcards to match multiple capabilities simultaneously.

* *Asterisk wildcard character (`{asterisk}`):* +
Matches capabilities with such a qualifier property no matter of its value (except `null` or `undefined`). Use it like this: `{property: '{asterisk}'}`.
* *Partial wildcard (`{asterisk}{asterisk}`):* +
Matches capabilities even if having additional properties. Use it like this: `{'{asterisk}': '{asterisk}'}`.

|===

[[chapter:intention-api:intent]]
=== What is an Intent?
The intent is the message that a micro application sends to interact with functionality that is available in the form of a capability.

An intent consists of a type and optionally a qualifier, which are used by the platform to identify the capability(s) to which to transport the intent. A micro application can issue an intent only if having declared a respective intention in its manifest. Along with the intent, you can pass transfer data, either as payload, message headers or parameters. Passed data must be serializable with the Structured Clone Algorithm.

The following code snippet illustrates how to send an intent.

[source,typescript]
----
include::intention-api.snippets.ts[tags=publish-intent]
----

The following code snippet illustrates how to pass parameters with an intent. Passed parameters must be defined in the capability, otherwise the intent would be rejected.

In the following example, we use an `authorization` param to pass along the authorization token.

[source,typescript]
----
include::intention-api.snippets.ts[tags=publish-intent-with-params]
----

For more information about publishing an intent, see the chapter <<chapter:intent-based-messaging:publishing-intent>> in <<chapter:intent-based-messaging>>.

[[chapter:intention-api:capability-lookup]]
=== Browsing Capabilities
A micro application can browse the catalog of capabilities using the `ManifestService`.

[.text-center]
image::lookup-capabilities.svg[]

Looking up capabilities allows the flexible composition of web content, such as populating a toolbar with items provided in the form of capabilities. A micro application can look up its own capabilities and public capabilities for which it has declared an intention.

In below example, a toolbar is composed of toolbar items contributed by micro applications in the form of capabilities. When the user clicks a toolbar item, the integrating app issues an intent, which the platform then transports to the providing micro application.

[.text-center]
image::capability-contribution.svg[]

The implementor of the toolbar can lookup toolbar item capabilities as follows:

[source,typescript]
----
include::intention-api.snippets.ts[tags=capability-lookup-toolbar-items]
----
<1> Looks up toolbar items for the main application toolbar.
<2> Issues an intent when the user clicks a toolbar item. For the intent, we use the type and qualifier of the capability. The micro application providing the capability does then handle the intent.

NOTE: To see how to handle intents in the capability providing micro application, see the chapter <<chapter:intent-based-messaging:receiving-intents>> in <<chapter:intent-based-messaging>>.

By passing a `ManifestObjectFilter` to the `lookupCapabilities$` method, you can control which capabilities to observe. Specified filter criteria are "AND"ed together. If not passing a filter, all capabilities visible to the requesting micro application are observed. When subscribing to the Observable, it emits the requested capabilities. The Observable never completes and emits continuously when fulfilling capabilities are registered or unregistered.

IMPORTANT: A micro application can only look up its own capabilities and public capabilities for which it has declared an intention.

.Properties of `ManifestObjectFilter` to filter capabilities
[cols="1,2,1,8"]
|===
| Property | Type | Mandatory | Description

| id
a| `string`
| no
| Observes a single capability of the given identity.

| type
a| `string`
| no
| Observes capabilities of a specific type.

| qualifier
a| `Dictionary`
| no
a|
Observes capabilities that match the qualifier.

If specifying a qualifier filter, the capabilities must match that filter exactly. The filter supports the asterisk wildcard to match any value, e.g., `{property: '{asterisk}'}`, or partial matching to find capabilities with at least the specified qualifier properties. Partial matching is enabled by appending the _any-more_ entry to the qualifier, as following: `{'{asterisk}': '{asterisk}'}`.

| appSymbolicName
a| `string`
| no
| Observes capabilities that are provided by a specific micro application.

|===

[[chapter:intention-api:intention-lookup]]
=== Browsing Intentions
The platform allows you to browse and observe intentions. Unlike <<chapter:intention-api:capability-lookup,browsing capabilities>>, an application can browse the intentions of all micro applications. The use case for browsing intentions is somewhat technical, e.g., used by the _DevTools_ to list intentions declared by micro applications.

You can browse intentions using the `ManifestService.lookupIntentions$` method. By passing a `ManifestObjectFilter` to the `lookupIntentions$` method, you can control which intentions to observe. Specified filter criteria are "AND"ed together. If not passing a filter, all intentions are observed. When subscribing to the Observable, it emits the requested intentions. The Observable never completes and emits continuously when matching intentions are registered or unregistered.

.Properties of `ManifestObjectFilter` to filter intentions
[cols="1,2,1,8"]
|===
| Property | Type | Mandatory | Description

| id
a| `string`
| no
| Observes a single intention of the given identity.

| type
a| `string`
| no
| Observes intentions of a specific type.

| qualifier
a| `Dictionary`
| no
a|
Observes intentions that match the qualifier.

If specifying a qualifier filter, the intentions must match that filter exactly. The filter supports the asterisk wildcard to match any value, e.g., `{property: '{asterisk}'}`, or partial matching to find intentions with at least the specified qualifier properties. Partial matching is enabled by appending the _any-more_ entry to the qualifier, as following: `{'{asterisk}': '{asterisk}'}`.

| appSymbolicName
a| `string`
| no
| Observes intentions that are provided by a specific micro application.

|===

[[chapter:intention-api:capability-registration]]
=== Registering Capabilities
Capabilities can be declared statically via the manifest file or registered at runtime via the `ManifestService`. Registering or unregistering capabilities at runtime enables a micro application to contribute functionality more flexibly. For example, a micro application could inform the user about an upcoming maintenance window by temporarily registering a notification capability.

[.text-center]
image::register-capabilities.svg[]

The following code snippet illustrates how to register a capability dynamically.

[source,typescript]
----
include::intention-api.snippets.ts[tags=capability-register-notification]
----
<1> Registers the capability to inform the user about planned maintenance.
<2> Unregisters the capability after 30 seconds.

For an overview of the supported capability properties, see chapter <<objects::capability>>.

TIP: Capabilities are typically registered in an activator. An activator is a special microfrontend that a micro application can provide to interact with the platform. Activators are loaded when starting the host application and run for the entire application lifecycle. For more information, refer to chapter <<chapter:activator>>.

'''

The host application, for example, can then observe these `user-notification` capabilities and display the message to the user.

[source,typescript]
----
include::intention-api.snippets.ts[tags=capability-lookup-notification]
----
<1> Observes `notification` capabilities.
<2> Displays each notification.

For more information about how observing capabilities, see chapter <<chapter:intention-api:capability-lookup>>.

[[chapter:intention-api:intention-registration]]
=== Registering Intentions
The platform allows registering or unregistering intentions at runtime. Note that this API is disabled by default.

IMPORTANT: It is discouraged to enable this API for a micro application. Instead, micro applications should declare their required functionality upfront in their manifest and use wildcards in their intention declarations. Otherwise, the advantage of the _Intention API_ would be weakened, since you no longer can statically inspect requirements of applications.

To enable this API for a specific micro application, unset the flag `intentionRegisterApiDisabled` when registering the app.

[source,typescript]
----
include::intention-api.snippets.ts[tags=enable-intention-register-api]
----
<1> Enables the API for the `Product Catalog Application`.

Similar to <<chapter:intention-api:capability-registration,registering a capability>>, you can register an intention using the `ManifestService` and its `registerIntention` method. For an overview of the supported intention properties, see chapter <<objects::intention>>.

[[chapter:intention-api:capability-interception]]
=== Intercepting Capabilities
The platform allows intercepting capabilities before they are registered, for example, to perform validation checks, add metadata, change properties, or prevent registration based on user permissions.

An interceptor must implement the `intercept` method of the `CapabilityInterceptor` interface.

The following interceptor assigns a stable identifier to each microfrontend capability.

[source,typescript]
----
include::intention-api.snippets.ts[tags=intercept-capability:intercept]
----

The following interceptor marks capabilities as inactive based on user permissions.

[source,typescript]
----
include::intention-api.snippets.ts[tags=intercept-capability:mark-inactive]
----

Alternatively, the capability can be rejected. Unlike inactive capabilities, rejected capabilities are not listed in the SCION DevTools.

[source,typescript]
----
include::intention-api.snippets.ts[tags=intercept-capability:reject]
----

An interceptor can add extra capabilities and intentions to the manifest of the intercepted capability. This may be necessary to migrate capabilities.

The following interceptor extracts user information to a new capability.

[source,typescript]
----
include::intention-api.snippets.ts[tags=intercept-capability:manifest]
----


Interceptors are registered in the bean manager of the host application under the symbol `CapabilityInterceptor` as `multi` bean. Multiple interceptors can be registered, forming a chain in which each interceptor is called one by one in registration order.

[source,typescript]
----
include::intention-api.snippets.ts[tags=register-capability-interceptor]
----
<1> Registers an interceptor to intercept capabilities. Interceptor must be registered before starting the platform.
<2> Starts the platform.

