:basedir: ../../..
include::{basedir}/_common.adoc[]

[[chapter:angular_integration_guide]]
== Angular Integration Guide
This part of the documentation is for developers who want to integrate the SCION Microfrontend Platform in an Angular application.

[.chapter-toc]
****
[.chapter-title]
In this Chapter

- <<chapter:angular-integration-guide:starting-platform-in-app-initializer>>
- <<chapter:angular-integration-guide:connecting-to-host-in-app-initializer>>
- <<chapter:angular-integration-guide:using-route-resolver-instead-app-initializer>>
- <<chapter:angular-integration-guide:configuring-hash-based-routing>>
- <<chapter:angular-integration-guide:activate-custom-elements-schema>>
- <<chapter:angular-integration-guide:providing-activator-services>>
- <<chapter:angular-integration-guide:providing-platform-beans-for-dependency-injection>>
- <<chapter:angular-integration-guide:providing-microfrontends-as-lazy-loaded-modules>>
- <<chapter:angular-integration-guide:synchronizing-rxjs-observables-with-angular-zone>>
****
'''

[[chapter:angular-integration-guide:starting-platform-in-app-initializer]]
[discrete]
=== Starting the Platform Host in an Angular App Initializer

The platform should be started during the bootstrapping of the Angular application, that is, before displaying content to the user. Hence, we recommend starting the platform in an app initializer. See chapter <<chapter:angular-integration-guide:using-route-resolver-instead-app-initializer>> for an alternative approach.

Angular allows hooking into the process of initialization by providing an initializer to Angular's `APP_INITIALIZER` injection token. Angular will wait until all initializers resolved to start the application, making it the ideal place for starting the SCION Microfrontend Platform.

NOTE: We recommend starting the platform outside of the Angular zone in order to avoid excessive change detection cycles of platform-internal subscriptions to global DOM events.

The following code snippet configures an Angular `APP_INITIALIZER` to start the platform. In the provider definition, we reference a higher order factory function and instruct Angular to inject the `PlatformInitializer` as function argument.

[source,typescript]
----
include::start-platform-via-initializer.snippets.ts[tags=host-app:register-initializer]
----
<1> Provides an initializer to the `APP_INITIALIZER` injection token.
<2> Instructs Angular to pass the `PlatformInitializer` to the higher order function.
<3> Returns the initializer function. When Angular invokes the initializer function, we delegate platform startup to the `PlatformInitializer` service.

IMPORTANT: Angular is very strict when compiling module definitions ahead-of-time (if enabled the AOT compilation). Therefore, you may need to replace the lambdas with the ES5 function syntax. Also, do not forget to export all functions that you reference in the module metadata definition.

Next, we implement the `PlatformInitializer` to start the platform.

[source,typescript]
----
include::start-platform-via-initializer.snippets.ts[tags=host-app:initializer]
----
<1> Injects the Angular `NgZone`.
<2> Declares or loads the platform config, e.g., using `HttpClient`.
<3> Starts the platform host. We recommend starting it outside of the Angular zone in order to avoid excessive change detection cycles.


====
TIP: Refer to chapter <<chapter:configuration:starting-the-platform-in-host-application>> for detailed instructions on how to start the platform in the host and micro applications.
====

[[chapter:angular-integration-guide:connecting-to-host-in-app-initializer]]
[discrete]
=== Connecting to the Host in an Angular App Initializer
A micro application should connect to the platform host during the bootstrapping of the Angular application, that is, before displaying content to the user. Hence, we recommend connecting to the platform host in an app initializer. See chapter <<chapter:angular-integration-guide:using-route-resolver-instead-app-initializer>> for an alternative approach.

NOTE: We recommend connecting to the platform host outside of the Angular zone in order to avoid excessive change detection cycles of platform-internal subscriptions to global DOM events.

[source,typescript]
----
include::start-platform-via-initializer.snippets.ts[tags=micro-app:initializer]
----
<1> Provides an initializer to the `APP_INITIALIZER` injection token.
<2> Instructs Angular to pass the `NgZone` to the higher order function. Alternatively, since Angular 14, you can inject the zone directly in the factory function with `inject(NgZone)`.
<3> Returns the initializer function, which connects to the host. We recommend connecting to the host outside of the Angular zone in order to avoid excessive change detection cycles.

[[chapter:angular-integration-guide:using-route-resolver-instead-app-initializer]]
[discrete]
=== Using a Route Resolver instead of an App Initializer
If you cannot use an app initializer for starting the platform or connecting to the platform host, an alternative would be to use a route resolver. Angular allows installing resolvers on a route, allowing data to be resolved asynchronously before the route is finally activated.

NOTE: We recommend connecting to the platform host outside of the Angular zone in order to avoid excessive change detection cycles of platform-internal subscriptions to global DOM events.

The following code snippet illustrates how to connect to the platform host using an Angular resolver. Similarly, you could start the platform in the host application.

For a micro application, the resolver implementation could look as following:

[source,typescript]
----
include::start-platform-via-resolver.snippets.ts[tags=resolver]
----
<1> Injects the Angular `NgZone`.
<2> Connects to the platform host. We recommend connecting to the host outside of the Angular zone in order to avoid excessive change detection cycles.

Ensure that a micro application instance connects to the host only once. Therefore, it is recommended to install the resolver in a parent route common to all microfrontend routes. When loading a microfrontend for the first time, Angular will wait activating the child route until the platform finished starting. When navigating to another microfrontend of the micro application, the resolver would not resolve anew.

[source,typescript]
----
include::start-platform-via-resolver.snippets.ts[tags=resolver-registration]
----
<1> Installs the resolver on a component-less, empty-path route, which is parent to the microfrontend routes.
<2> Registers microfrontend routes as child routes.

[[chapter:angular-integration-guide:configuring-hash-based-routing]]
[discrete]
=== Configuring Hash-Based Routing
We recommend using hash-based routing over HTML 5 push-state routing in micro applications. To enable hash-based routing in an Angular application, pass `{useHash: true}` when configuring the router in `AppRoutingModule`, as follows.

[source,typescript]
----
include::angular-integration-guide.snippets.ts[tags=configure-hash-based-routing]
----

If you use hash-based routing, do not forget to set the base URL of the application to `#` in the manifest, as follows:

[source,json]
----
include::angular-integration-guide.snippets.ts[tags=configure-hash-based-routing-set-baseurl]
----

====
TIP: Read chapter <<chapter:miscellaneous:routing-in-micro-applications>> to learn more about why to prefer hash-based routing.
====

[[chapter:angular-integration-guide:activate-custom-elements-schema]]
[discrete]
=== Instruct Angular to allow Custom Elements in Templates
The `<sci-router-outlet>` element for embedding microfrontends is a custom element according to the web component standard. We must tell Angular that we are using custom elements in our templates that are not registered Angular components. Otherwise, the Angular compiler would complain.

Doing this is straightforward. In your app module, add the `CUSTOM_ELEMENTS_SCHEMA` schema to allow the use of custom elements, as follows:

[source,typescript]
----
include::angular-integration-guide.snippets.ts[tags=add-custom-elements-schema]
----

[[chapter:angular-integration-guide:providing-activator-services]]
[discrete]
=== Providing Activator Services
====
TIP: Read chapter <<chapter:activator>> to learn more about activators.
====

In order to install an activator, you need to register an _activator_ capability in your manifest.

[source,json]
----
include::activator.snippets.ts[tags=activator-capability]
----
<1> Activators have the type `activator`.
<2> Activators must have public visibility.
<3> Path where the platform can load the activator microfrontend. The path is relative to the base URL of the micro application, as specified in the application manifest.

We recommend creating a component-less, lazy-loaded activator module, that you register as routing target for the _activator_ path specified in the manifest.

[source,typescript]
----
include::activator.snippets.ts[tags=activator-route]
----

The activator module declares a DI token under which you can register one or more activator services. By injecting the DI token into the module constructor, Angular constructs all registered activator services.

The module implementation could look similar to the following:

[source,typescript]
----
include::activator.snippets.ts[tags=activator-module]
----
<1> Declares a DI token under which you can register activator services. If you use Angular 9 or later, you do not need to export the token.
<2> By way of example, registers the `AuthenticatorService` as activator service, e.g., to obtain the user's access token and preemtively refresh it before its expected expiration.
<3> By way of example, registers the `MicrofrontendRouter` as activator service, e.g., to handle microfrontend intents, instructing the router to navigate.
<4> Installs an empty routes array. Do not omit the empty routes definition, as otherwise, route resolvers, if any, would be resolved multiple times.
<5> Injects registered activator services in order to construct them.

It turned out that when using a route resolver to start the platform, Angular constructs the activator module instantly, that is, before the `PlatformInitializer` returns. For this reason, if you start the platform within a route resolver, and only then, you must wait to inject the activator services until the platform finished starting.

The module constructor would then look as follows:

[source,typescript]
----
include::activator.snippets.ts[tags=activator-module-using-resolver]
----
<1> Waits until the platform started; only required if starting the platform in a resolver.
<2> Injects registered activator services via Angular `Injector`.

Activator can perform activation tasks in the constructor.

[source,typescript]
----
include::activator.snippets.ts[tags=activator-services]
----

[[chapter:angular-integration-guide:providing-platform-beans-for-dependency-injection]]
[discrete]
=== Providing Platform Beans for Dependency Injection
With Angular, it is easy to provide platform-specific beans for dependency injection using the factory provider definition, allowing objects managed by Angular to constructor-inject platform beans.

[source,typescript]
----
include::angular-integration-guide.snippets.ts[tags=provide-platform-beans-for-dependency-injection]
----

[[chapter:angular-integration-guide:providing-microfrontends-as-lazy-loaded-modules]]
[discrete]
=== Providing Microfrontends as Lazy-Loaded Modules
For good user experience, microfrontends should have a fast bootstrap time and load only the modules and data they need. Therefore, we recommend providing microfrontends as small, lazy-loaded modules grouped by functionality.

[source,typescript]
----
include::lazy-loaded-modules.snippets.ts[tags=routes]
----
<1> Registers the lazy-loaded route for the `microfrontend-1` microfrontend.
<2> Registers the lazy-loaded route for the `microfrontend-2` microfrontend.
<3> Registers the lazy-loaded route for the `activator` microfrontend.

A microfrontend module could look similar to the following:

[source,typescript]
----
include::lazy-loaded-modules.snippets.ts[tags=microfrontend-1-module]
----

[[chapter:angular-integration-guide:synchronizing-rxjs-observables-with-angular-zone]]
[discrete]
=== Synchronizing RxJS Observables with the Angular Zone

Angular applications expect an RxJS Observable to emit in the same Angular zone in which subscribed to the Observable. That is, if subscribing inside the Angular zone, emissions are expected to be received inside the Angular zone. Otherwise, the UI may not be updated as expected but delayed until the next change detection cycle. Similarly, if subscribing outside the Angular zone, emissions are expected to be received outside the Angular zone. Otherwise, this would cause unnecessary change detection cycles resulting in potential performance degradation.

Therefore, the platform supports the decoration of its observables to emit in the correct zone. We strongly recommend decoration for Angular applications. A decorator must implement `ObservableDecorator` and be registered in the bean manager before the platform is started, as follows:

[source,typescript]
----
include::angular-zone-observable-decorator.snippets.ts[tags=register-ng-zone-observable-decorator]
----
<1> Injects the Angular `NgZone`.
<2> Registers the decorator.

Example of a decorator for synchronizing the Angular zone.

[source,typescript]
----
include::angular-zone-observable-decorator.snippets.ts[tags=ng-zone-observable-decorator]
----
<1> Captures the zone at the time of subscription to the Observable.
<2> Subscribes to the source outside of the Angular zone.
<3> Runs subscription handlers (`next`, `error`, `complete`) in the same zone in which subscribed to the Observable.

