:basedir: ../../..
include::{basedir}/_common.adoc[]

[[chapter:angular_integration_guide]]
== Angular Integration Guide
This part of the documentation is for developers who want to integrate the SCION Microfrontend Platform in an Angular application.

[.chapter-toc]
****
[.chapter-title]
In this Chapter

- <<chapter:angular-integration-guide:starting-platform-in-app-initializer>>
- <<chapter:angular-integration-guide:connecting-to-host-in-app-initializer>>
- <<chapter:angular-integration-guide:using-route-resolver-instead-app-initializer>>
- <<chapter:angular-integration-guide:configuring-hash-based-routing>>
- <<chapter:angular-integration-guide:activate-custom-elements-schema>>
- <<chapter:angular-integration-guide:providing-activator>>
- <<chapter:angular-integration-guide:providing-platform-beans-for-dependency-injection>>
- <<chapter:angular-integration-guide:providing-microfrontends>>
- <<chapter:angular-integration-guide:synchronizing-rxjs-observables-with-angular-zone>>
****
'''

[[chapter:angular-integration-guide:starting-platform-in-app-initializer]]
[discrete]
=== Starting the Platform Host in an Angular App Initializer

The platform should be started during the bootstrapping of the Angular application, that is, before displaying content to the user. Hence, we recommend starting the platform in an app initializer. See chapter <<chapter:angular-integration-guide:using-route-resolver-instead-app-initializer>> for an alternative approach.

NOTE: Angular allows hooking into the process of initialization by providing an initializer to Angular's `APP_INITIALIZER` injection token. Angular will wait until all initializers resolved to start the application, making it the ideal place for starting the SCION Microfrontend Platform.

IMPORTANT: We recommend starting the platform outside the Angular zone in order to avoid excessive change detection cycles of platform-internal subscriptions to global DOM events.

The following listing illustrates how to configure an Angular `APP_INITIALIZER` to start the SCION Microfrontend Platform in the host application. Note that `APP_INITIALIZER` expects a higher order factory function to be specified.

[source,typescript]
----
include::start-platform-via-initializer.snippets.ts[tags=host-app:startPlatformHost]
----
<1> Registers a set of DI providers to set up the SCION Microfrontend Platform in the host application.
<2> Instruments Angular to start the SCION Microfrontend Platform during application startup.
<3> Injects `NgZone` using Angular's `inject` function.
<4> Registers a decorator to synchronize platform-specific RxJS Observables with the Angular Zone. See <<chapter:angular-integration-guide:synchronizing-rxjs-observables-with-angular-zone>> for more information.
<5> Constructs the config object to configure the platform and list applications that are allowed to interact with the platform. Refer to <<chapter:configuration:configuring-the-platform>> for more information about configuring the platform.
<6> Starts the platform host outside the Angular zone.


====
TIP: Refer to chapter <<chapter:configuration:starting-the-platform-in-host-application>> for detailed instructions on how to start the platform in the host.
====

[[chapter:angular-integration-guide:connecting-to-host-in-app-initializer]]
[discrete]
=== Connecting to the Host in an Angular App Initializer
A micro application should connect to the platform host during the bootstrapping of the Angular application, that is, before displaying content to the user. Hence, we recommend connecting to the platform host in an app initializer. See chapter <<chapter:angular-integration-guide:using-route-resolver-instead-app-initializer>> for an alternative approach.

NOTE: Angular allows hooking into the process of initialization by providing an initializer to Angular's `APP_INITIALIZER` injection token. Angular will wait until all initializers resolved to start the application, making it the ideal place for starting the SCION Microfrontend Platform.

IMPORTANT: We recommend connecting to the platform host outside the Angular zone in order to avoid excessive change detection cycles of platform-internal subscriptions to global DOM events.

The following listing illustrates how to configure an Angular `APP_INITIALIZER` to connect to the platform from a micro application.

[source,typescript]
----
include::start-platform-via-initializer.snippets.ts[tags=micro-app:connectToHost]
----
<1> Registers a set of DI providers to set up the SCION Microfrontend Platform in a client application.
<2> Instruments Angular to connect to the platform host during application startup.
<3> Injects `NgZone` using Angular’s `inject` function.
<4> Registers a decorator to synchronize platform-specific RxJS Observables with the Angular Zone. See <<chapter:angular-integration-guide:synchronizing-rxjs-observables-with-angular-zone>> for more information.
<5> Connects to the platform host outside the Angular zone, passing the symbolic name of the application as argument.

====
TIP: Refer to chapter <<chapter:configuration:connecting-to-the-host>> for detailed instructions on how to connect to the host from a microfrontend.
====

[[chapter:angular-integration-guide:using-route-resolver-instead-app-initializer]]
[discrete]
=== Using a Route Resolver instead of an App Initializer
If you cannot use an app initializer for starting the platform or connecting to the platform host, an alternative would be to use a route resolver. Resolvers can be used to resolve data or run code prior to route activation.

The following listing illustrates how to configure an Angular resolver to connect to the platform from a client application. Similarly, you could start the platform in the host application.

[source,typescript]
----
include::start-platform-via-resolver.snippets.ts[tags=resolver]
----
<1> Installs a resolver on a component-less, empty-path route, which is parent to the microfrontend routes.
<2> Injects `NgZone` using Angular’s `inject` function.
<3> Registers a decorator to synchronize platform-specific RxJS Observables with the Angular Zone. See <<chapter:angular-integration-guide:synchronizing-rxjs-observables-with-angular-zone>> for more information.
<4> Connects to the platform host outside the Angular zone, passing the symbolic name of the application as argument.
<5> Registers microfrontend routes as child routes.

Ensure that a micro application instance connects to the host only once. Therefore, it is recommended to install the resolver in a parent route common to all microfrontend routes. When loading a microfrontend for the first time, Angular will wait activating the child route until the platform finished starting. When navigating to another microfrontend of the micro application, the resolver does not resolve anew.


[[chapter:angular-integration-guide:configuring-hash-based-routing]]
[discrete]
=== Configuring Hash-Based Routing
For client applications, we recommend enabling hash-based routing for the reasons explained in <<chapter:miscellaneous:routing-in-micro-applications>>. For the host application, either strategy is fine.

To enable hash-based routing, pass the `withHashLocation()` feature to the router, as follows:

[source,typescript]
----
include::angular-integration-guide.snippets.ts[tags=configure-hash-based-routing]
----

If you use hash-based routing, do not forget to set the base URL of the application to `#` in the manifest, as follows:

[source,json]
----
include::angular-integration-guide.snippets.ts[tags=configure-hash-based-routing-set-baseurl]
----

[[chapter:angular-integration-guide:activate-custom-elements-schema]]
[discrete]
=== Instruct Angular to allow Custom Elements in Templates
The `<sci-router-outlet>` element for embedding microfrontends is a custom element according to the web component standard. For use in an Angular component, we need to tell the Angular compiler that we are using non-Angular elements. Otherwise, the compiler would complain that `<sci-router-outlet>` cannot be resolved to an Angular component.

For standalone components, set the `CUSTOM_ELEMENTS_SCHEMA` schema in the component metadata as follows:

[source,typescript]
----
include::angular-integration-guide.snippets.ts[tags=add-custom-elements-schema]
----

The `schemas` property is only available for standalone components. For components declared in an `NgModule`, set the schema in the module metadata instead.

[[chapter:angular-integration-guide:providing-activator]]
[discrete]
=== Providing an Activator
====
TIP: Read chapter <<chapter:activator>> to learn more about activators.
====

In order to install an activator, you need to register an _activator_ capability in your manifest.

[source,json]
----
include::activator.snippets.ts[tags=activator-capability]
----
<1> Activators have the type `activator`.
<2> Activators must have public visibility.
<3> Path where the platform can load the activator microfrontend. The path is relative to the base URL of the micro application, as specified in the application manifest.

We recommend creating a component-less, lazy-loaded activator module and registering it under the _activator_ path as specified in the manifest.

[source,typescript]
----
include::activator.snippets.ts[tags=activator-route]
----

The module will be instantiated when the platform loads registered activators. In the module constructor, you can perform initialization tasks such as installing message handlers.

[source,typescript]
----
include::activator.snippets.ts[tags=activator-module]
----
<1> Declares the activator `NgModule`. No further metadata is required.
<2> Performs initialization tasks such as installing message handlers.


[NOTE]
====
It turned out that when using a route resolver to start the platform, Angular constructs the activator module immediately, that is, before the resolver completes. For this reason, if you start the platform inside a route resolver, and only then, you must wait for the platform to complete startup before interacting with the platform, as follows:

[source,typescript]
----
include::activator.snippets.ts[tags=activator-module-using-resolver]
----
====

[[chapter:angular-integration-guide:providing-platform-beans-for-dependency-injection]]
[discrete]
=== Providing Platform Beans for Dependency Injection
Beans of the SCION Microfrontend Platform can be provided for dependency injection, allowing objects managed by Angular to inject platform beans.

[source,typescript]
----
include::angular-integration-guide.snippets.ts[tags=provide-platform-beans-for-dependency-injection]
----

[[chapter:angular-integration-guide:providing-microfrontends]]
[discrete]
=== Providing Microfrontends as Standalone Lazy-Loaded Components
Microfrontends should have a fast startup time and therefore only load code and data that they need. Therefore, we recommend providing microfrontends as standalone, lazy-loaded components.

[source,typescript]
----
include::lazy-loaded-microfrontends.snippets.ts[tags=routes]
----
<1> Registers the lazy-loaded route for the `activator` microfrontend.
<2> Registers the lazy-loaded route for the `microfrontend-1` microfrontend.
<3> Registers the lazy-loaded route for the `microfrontend-2` microfrontend.
<4> Registers the declared routes with Angular.


[[chapter:angular-integration-guide:synchronizing-rxjs-observables-with-angular-zone]]
[discrete]
=== Synchronizing RxJS Observables with the Angular Zone

Angular applications expect an RxJS Observable to emit in the same Angular zone in which subscribed to the Observable. That is, if subscribing inside the Angular zone, emissions are expected to be received inside the Angular zone. Otherwise, the UI may not be updated as expected but delayed until the next change detection cycle. Similarly, if subscribing outside the Angular zone, emissions are expected to be received outside the Angular zone. Otherwise, this would cause unnecessary change detection cycles resulting in potential performance degradation.

Therefore, the platform supports the decoration of its observables to emit in the correct zone. We strongly recommend decoration for Angular applications. A decorator must implement `ObservableDecorator` and be registered in the bean manager before the platform is started, as follows:

[source,typescript]
----
include::angular-zone-observable-decorator.snippets.ts[tags=register-ng-zone-observable-decorator]
----
<1> Injects the Angular `NgZone`.
<2> Registers the decorator.

Example of a decorator for synchronizing the Angular zone.

[source,typescript]
----
include::angular-zone-observable-decorator.snippets.ts[tags=ng-zone-observable-decorator]
----
<1> Captures the zone at the time of subscription to the Observable.
<2> Subscribes to the source outside the Angular zone.
<3> Runs subscription handlers (`next`, `error`, `complete`) in the same zone in which subscribed to the Observable.

